---
- name: Manage Tomcat
  hosts: localhost
  become: yes
  connection: local
  tasks:
    - name: Gather facts about the system
      setup:

    - name: Check if running on a Debian-based system
      fail:
        msg: "This playbook requires a Debian-based system."
      when: ansible_os_family != "Debian"

    - name: Ensure Java 11 is installed
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

    - name: Install Tomcat
      apt:
        name: tomcat9
        state: present

    - name: Start Tomcat
      systemd:
        name: tomcat9
        state: started

    - name: Stop Tomcat
      systemd:
        name: tomcat9
        state: stopped
