---
- name: Manage Tomcat
  hosts: localhost
  become: yes
  connection: local
  tasks:
    - name: Ensure Java is installed
      package:
        name: java-1.8.0-openjdk
        state: present

    - name: Download Tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.62/bin/apache-tomcat-9.0.62.tar.gz
        dest: /tmp/apache-tomcat-9.0.62.tar.gz

    - name: Extract Tomcat
      unarchive:
        src: /tmp/apache-tomcat-9.0.62.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Start Tomcat
      command: /opt/apache-tomcat-9.0.62/bin/startup.sh

    - name: Stop Tomcat
      command: /opt/apache-tomcat-9.0.62/bin/shutdown.sh
