---
- name: Manage Tomcat
  hosts: localhost
  become: yes
  connection: local
  tasks:
    - name: Gather facts about the system
      setup:

    - name: Print the operating system information
      debug:
        msg: "OS: {{ ansible_distribution }} Version: {{ ansible_distribution_version }}"

    - name: Check for network connectivity
      command: ping -c 1 google.com
      register: ping_result
      failed_when: ping_result.rc != 0

    - name: Ensure Java 11 is installed on RedHat-based systems
      yum:
        name: java-11-openjdk
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Tomcat on RedHat-based systems
      yum:
        name: tomcat
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start Tomcat
      systemd:
        name: tomcat
        state: started

    - name: Stop Tomcat
      systemd:
        name: tomcat
        state: stopped
