---
- name: Manage Tomcat
  hosts: localhost
  become: yes
  connection: local
  tasks:
    - name: Check internet connectivity
      command: ping -c 1 google.com
      register: ping_result
      failed_when: ping_result.rc != 0

    - name: Gather facts
      setup:

    - name: Ensure dependencies are installed
      package:
        name: 
          - python3-apt
        state: present
      when: ansible_os_family == 'Debian'
      
    - name: Ensure Tomcat is installed
      package:
        name: 
          - tomcat9
        state: present
      become: yes

    - name: Start Tomcat
      systemd:
        name: tomcat9
        state: started
      register: tomcat_start_status

    - name: Debug Tomcat start status
      debug:
        var: tomcat_start_status

    - name: Stop Tomcat
      systemd:
        name: tomcat9
        state: stopped
      become: yes
