---
- name: Manage Tomcat
  hosts: localhost
  become: yes
  connection: local
  tasks:
    - name: Gather facts about the system
      setup:

    - name: Print the operating system information
      debug:
        msg: "OS: {{ ansible_distribution }} Version: {{ ansible_distribution_version }}"

    - name: Check for network connectivity
      command: ping -c 1 google.com
      register: ping_result
      ignore_errors: yes

    - name: Ensure Java 11 is installed on Ubuntu
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Ensure Java 11 is installed on CentOS
      yum:
        name: java-11-openjdk
        state: present
      when: ansible_distribution == "CentOS"

    - name: Install Tomcat on Ubuntu
      apt:
        name: tomcat9
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install Tomcat on CentOS
      yum:
        name: tomcat
        state: present
      when: ansible_distribution == "CentOS"

    - name: Start Tomcat on Ubuntu
      systemd:
        name: tomcat9
        state: started
      when: ansible_distribution == "Ubuntu"

    - name: Start Tomcat on CentOS
      systemd:
        name: tomcat
        state: started
      when: ansible_distribution == "CentOS"

    - name: Stop Tomcat on Ubuntu
      systemd:
        name: tomcat9
        state: stopped
      when: ansible_distribution == "Ubuntu"

    - name: Stop Tomcat on CentOS
      systemd:
        name: tomcat
        state: stopped
      when: ansible_distribution == "CentOS"
