---
- name: Manage Tomcat
  hosts: localhost
  become: yes
  connection: local
  tasks:
    - name: Start Tomcat
      systemd:
        name: tomcat
        state: started
    - name: Stop Tomcat
      systemd:
        name: tomcat
        state: stopped
