---
- name: Manage Tomcat
  hosts: localhost
  become: yes
  connection: local
  tasks:
    - name: Ensure Tomcat is installed
      apt:
        name: tomcat9
        state: present

    - name: Start Tomcat
      systemd:
        name: tomcat9
        state: started
      register: tomcat_start_status

    - name: Debug Tomcat start status
      debug:
        var: tomcat_start_status

    - name: Stop Tomcat
      systemd:
        name: tomcat9
        state: stopped
