---
- name: Manage Tomcat
  hosts: localhost
  become: yes
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ensure python3-apt is installed
      apt:
        name: python3-apt
        state: present
        update_cache: yes
      become: yes
      when: ansible_os_family == 'Debian'

    - name: Ensure Tomcat is installed
      apt:
        name: tomcat9
        state: present
        update_cache: no
      become: yes

    - name: Start Tomcat
      systemd:
        name: tomcat9
        state: started
      register: tomcat_start_status

    - name: Debug Tomcat start status
      debug:
        var: tomcat_start_status

    - name: Stop Tomcat
      systemd:
        name: tomcat9
        state: stopped
      become: yes
