---
- name: Manage Tomcat
  hosts: localhost
  become: yes
  connection: local
  tasks:
    - name: Gather facts about the system
      setup:

    - name: Print the operating system information
      debug:
        msg: "OS: {{ ansible_distribution }} Version: {{ ansible_distribution_version }}"

    - name: Check for network connectivity
      command: ping -c 1 google.com
      register: ping_result
      ignore_errors: yes

    - name: Ensure Java 11 is installed
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Tomcat
      apt:
        name: tomcat9
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Start Tomcat
      systemd:
        name: tomcat9
        state: started
      when: ansible_distribution == "Ubuntu"

    - name: Stop Tomcat
      systemd:
        name: tomcat9
        state: stopped
      when: ansible_distribution == "Ubuntu"
